---
abstract: 'type constraints for UUIDs'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.96'
  Test::TypeTiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Types-UUID
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Types::UUID:
    file: lib/Types/UUID.pm
    version: '0.004'
requires:
  Type::Tiny: '1.000000'
  UUID::Tiny: '1.02'
  perl: '5.008'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Types-UUID/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-UUID
  homepage: https://metacpan.org/release/Types-UUID
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-types-uuid.git
version: '0.004'
